### ISSUE TITLE
天地图中的聚合Marker组件如何使用？

### ISSUE THREAD

**Issue by rttg125** [SoulLyoko/vue-tianditu#12]
您好，我想在系统中引用天地图的聚合Marker组件，该如何在本组件中集成使用？

        var zoom = 3;
        var map;
        function onLoad() {
            map = new T.Map('mapDiv', {
                attributionControl: false,
                inertia: false
            });
            map.centerAndZoom(new T.LngLat(116.40969, 37.43997405227057), zoom);

            var arrayObj = new Array();
            for (var i = 0; i < 500; i++) {
                var marker = new T.Marker(new T.LngLat(Math.random() * 40 + 85, Math.random() * 30 + 21), {title: i});
                arrayObj.push(marker);
            }
            var markers = new T.MarkerClusterer(map, {markers: arrayObj});
        }

![](https://ftp.bmp.ovh/imgs/2021/03/de0c623df21871b5.png)

**Comment by SoulLyoko** [comment]
您可以在地图初始化事件中获取到map实例，此时用官方示例中的代码就可以实现：
```js
<tdt-map :center="center" :zoom="zoom" @init="mapInit">
......
methods:{
    mapInit(map) {
      const arrayObj = new Array();
      for (let i = 0; i < 500; i++) {
        const marker = new T.Marker(new T.LngLat(Math.random() * 40 + 85, Math.random() * 30 + 21), { title: i });
        arrayObj.push(marker);
      }
      const markers = new T.MarkerClusterer(map, { markers: arrayObj });
    }
}
```
或者待我稍后有空把这个组件集成进来

**Comment by SoulLyoko** [comment]
点聚合组件已更新，查看最新的文档来使用

**Comment by NoviceXiaobaicheng** [comment]
如何自定义根据聚焦数量显示颜色，尝试很多方法不管用
