### ISSUE TITLE
无法显示底图

### ISSUE THREAD

**Issue by ZBK1nger** [SoulLyoko/vue-tianditu#13]
请问，按照NPM的方式安装，无法显示出底图，且无报错信息~

**Comment by SoulLyoko** [comment]
你可以检查一下你的代码是否已在<tdt-map>组件传入正确的center和zoom，以及外层容器是否有固定的宽高。

**Comment by ZBK1nger** [comment]
我是新建了一个项目 ，在main.js引入，之后在App.vue粘贴你demo中的基础示例，你的基础示例，宽高和zoom、center都是有的，我在看下原因吧~
