### ISSUE TITLE
我在项目使用NPM安装后 全局引用 但一直报错  Require self-closing on Vue.js custom components (<tdt-map>) 

### ISSUE THREAD

**Issue by mis-czx** [SoulLyoko/vue-tianditu#16]

**Comment by mis-czx** [comment]
调整为  <tdt-map :center="center" :zoom="zoom" @click="mapClick" /> 错误消失

但是 就完全不显示了

**Comment by mis-czx** [comment]
tdt-map的 样式 宽 高 全是0  网路也无访问天地图

**Comment by SoulLyoko** [comment]
您好，感谢您的反馈！不过还是麻烦你把复现的代码、使用的版本以及具体的报错信息贴出来，我这边也好排查。如果可以把复现的代码建个仓库就最好了！

**Comment by mis-czx** [comment]
![mainjs](https://user-images.githubusercontent.com/76762702/117228646-0932be00-ae4c-11eb-9f50-367748530782.png)
![业务](https://user-images.githubusercontent.com/76762702/117228649-0b951800-ae4c-11eb-967f-9308eb862849.png)

很抱歉因为老板严令禁止以代码形式上传到任何网站, 我只能截图给您,方便您查阅
使用的安装命令是  npm i vue-tianditu  --save

**Comment by SoulLyoko** [comment]
发现你的问题了，你应该这样使用`<tdt-map :center="center" :zoom="zoom"></tdt-map>`，而不是使用自闭合标签

**Comment by SoulLyoko** [comment]
初始化配置中的tk也不能乱填，需要自行在天地图官网申请token。并且我发现你使用的是vue3.0版本，tdt组件库目前还不支持vue3.0哦。

**Comment by mis-czx** [comment]
初始化配置中的tk是有内容的 截图前修改了, 
因为tdt-map内无内容必须使用自动闭合不然会报错,
 额我是用的是VUE3  版本什么时候会更新呢

**Comment by SoulLyoko** [comment]
支持vue3的时间未定，但后续肯定会支持的。

**Comment by mis-czx** [comment]
非常感谢
