### ISSUE TITLE
按需引入时报子组件没注册

### ISSUE THREAD

**Issue by sunshoutian** [SoulLyoko/vue-tianditu#19]
比如使用 tdt-polygon ，能给个完整例子吗？文档里没有import这个子组件。谢谢。

控制台：
vue.runtime.esm.js?5593:619 [Vue warn]: Unknown custom element: <tdt-polygon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

使用方法直接copy文档上的。

**Comment by SoulLyoko** [comment]
不好意思！polygon组件在导出时名称拼写错了，现已修复，升级到1.2.10。
