### ISSUE TITLE
您好作者 问个体外问题 VUE3 加载天地图是报错

### ISSUE THREAD

**Issue by mis-czx** [SoulLyoko/vue-tianditu#24]
<template>
  <div id="tianditu" class="index-container">
    <div id="tianditu" ref="tianditu" class="tianditu"></div>
  </div>
</template>

<script>
  import { reactive, toRefs } from 'vue'
  export default {
    name: 'Index',
    setup() {
      const state = reactive({
        tdtMap: {},
      })

> 

      const initTdtMap = () => {
        state.tdtMap = new window.T.Map('tianditu')
        state.tdtMap.centerAndZoom(
          new window.T.LngLat(116.397128, 39.916527),
          16
        )
      }
      initTdtMap()
      return {
        ...toRefs(state),
      }
    },
  }
</script>

这段代码运行后会提示
Cannot read property '_tdt_events' of null
很郁闷 恳求作者谢谢

**Comment by SoulLyoko** [comment]
你好，当前版本还不支持vue3，下个大版本正在开发中哈

**Comment by SoulLyoko** [comment]
你可能需要在onMounted钩子中初始化天地图:
```js
import {onMounted} from "vue"

onMounted(()=>{
   initTdtMap();
})
```

**Comment by mis-czx** [comment]
非常感谢,已经可以了
