### ISSUE TITLE
Firefox 地图无法鼠标滚轮缩放

### ISSUE THREAD

**Issue by trdmm** [SoulLyoko/vue-tianditu#25]
Firefox: 89  ,  90.0.1
OS: Win10 20H2 , Linux

Firefox 滚轮无法缩放,Chromium系的没问题.
文档 [基础地图](https://soullyoko.github.io/vue-tianditu/map/map.html#%E7%A4%BA%E4%BE%8B) 这里面的地图在Firefox中也不能通过鼠标滚轮缩放.

**Comment by SoulLyoko** [comment]
这是天地图官方代码的问题，你可以为你的程序添加如下代码来兼容firefox的滚轮监听事件，前提是先禁用地图组件原来的滚轮事件
```
<tdt-map ref="map" :scrollWheelZoom="false" @init="mapInit"></tdt-map>

<script>
export default {
  methods: {
    mapInit(map) {
      this.$refs.map.$el.addEventListener("DOMMouseScroll", e => {
        e.preventDefault();
        e.detail > 0 ? map.zoomOut() : map.zoomIn();
      });
    }
  }
};
</script>
```

**Comment by trdmm** [comment]
> 这是天地图官方代码的问题，你可以为你的程序添加如下代码来兼容firefox的滚轮监听事件，前提是先禁用地图组件原来的滚轮事件
> 
> ```
> <tdt-map ref="map" :scrollWheelZoom="false" @init="mapInit"></tdt-map>
> 
> <script>
> export default {
>   methods: {
>     mapInit(map) {
>       this.$refs.map.$el.addEventListener("DOMMouseScroll", e => {
>         e.preventDefault();
>         e.detail > 0 ? map.zoomOut() : map.zoomIn();
>       });
>     }
>   }
> };
> </script>
> ```

好的,谢谢解答 :P
