### ISSUE TITLE
使用demo提示T.LngLat is not a constructor

### ISSUE THREAD

**Issue by ch634421335** [SoulLyoko/vue-tianditu#34]
vue是2.0，全局引用还是按需引用都提示这个问题。center和zoom设置后地图也无法加载

**Comment by SoulLyoko** [comment]
> vue是2.0，全局引用还是按需引用都提示这个问题。center和zoom设置后地图也无法加载

你是使用vue-tianditu v1还是v2？

**Comment by ch634421335** [comment]
> > vue是2.0，全局引用还是按需引用都提示这个问题。center和zoom设置后地图也无法加载
> 
> 你是使用vue-tianditu v1还是v2？

使用的v1 "vue-tianditu": "^1.2.11",

**Comment by SoulLyoko** [comment]
> vue是2.0，全局引用还是按需引用都提示这个问题。center和zoom设置后地图也无法加载

能提供复现的代码吗？

**Comment by ch634421335** [comment]
```
<template>
<div class="mapDiv">
  <tdt-map :center="center" :zoom="zoom"></tdt-map>
</div>
</template>

<script>
export default {
  name: "tianditu",
  data() {
    return {
      center: [116.40969,39.89945],
      zoom: 11
    }
  },
}
</script>

<style scoped>
.mapDiv{
  width: 100%;
  height: 100%;
}
</style>

```
![image](https://user-images.githubusercontent.com/46257384/140448380-9b46fdcd-91a5-46b5-a08d-a7fda213eed5.png)

**Comment by SoulLyoko** [comment]
> ```
> <template>
> <div class="mapDiv">
>   <tdt-map :center="center" :zoom="zoom"></tdt-map>
> </div>
> </template>
> 
> <script>
> export default {
>   name: "tianditu",
>   data() {
>     return {
>       center: [116.40969,39.89945],
>       zoom: 11
>     }
>   },
> }
> </script>
> 
> <style scoped>
> .mapDiv{
>   width: 100%;
>   height: 100%;
> }
> </style>
> ```
> 
> ![image](https://user-images.githubusercontent.com/46257384/140448380-9b46fdcd-91a5-46b5-a08d-a7fda213eed5.png)

请问是否有使用自己的注册的token引入组件：
Vue.use(VueTianditu, {
  v: "4.0",
  tk: "在这里填你在天地图官网注册的token"
});

**Comment by ch634421335** [comment]
> > ```
> > <template>
> > <div class="mapDiv">
> >   <tdt-map :center="center" :zoom="zoom"></tdt-map>
> > </div>
> > </template>
> > 
> > <script>
> > export default {
> >   name: "tianditu",
> >   data() {
> >     return {
> >       center: [116.40969,39.89945],
> >       zoom: 11
> >     }
> >   },
> > }
> > </script>
> > 
> > <style scoped>
> > .mapDiv{
> >   width: 100%;
> >   height: 100%;
> > }
> > </style>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/46257384/140448380-9b46fdcd-91a5-46b5-a08d-a7fda213eed5.png)
> 
> 请问是否有使用自己的注册的token引入组件： Vue.use(VueTianditu, { v: "4.0", tk: "在这里填你在天地图官网注册的token" });

有的 在main.js中注册了
```
import VueTianditu from "vue-tianditu";

Vue.use(VueTianditu,{
  v:'3.0',
  tk:''
})
```

**Comment by SoulLyoko** [comment]
```
```

**Comment by ch634421335** [comment]
改为4.0后可以使用了，非常感谢帮助！
