### ISSUE TITLE
使用内网部署的天地图控件加载不出来

### ISSUE THREAD

**Issue by ch634421335** [SoulLyoko/vue-tianditu#35]
我们公司要求使用内网部署的天地图，我把node_modules/vue-tianditu/lib下的三个js文件中天地图官网地址都改成内网地址后地图可以加载出来，鼠标控制放大缩小拖拽均没有问题。  
但是<td-map>只有center和zoom属性生效，其他的均无效，包括controls，tdt-label,tdt-marker。
现在控制台报错
```
Uncaught (in promise) TypeError:
e["enable".concat(...)] is not a function
```  
我看了下这个问题是在vue-tianditu.umd.min.js中
使用vue2 vue-tianditu v1.2.11  
大佬能否指导一下问题出在哪里

**Comment by SoulLyoko** [comment]
特殊的环境建议还是自己fork一份代码进行修改吧，这个我没办法帮你解决。
