### ISSUE TITLE
mapTypes不生效以及position不生效

### ISSUE THREAD

**Issue by Haifeng-work** [SoulLyoko/vue-tianditu#40]
设置了mapTypes和position都不生效， 这是为啥？
controls: [
    {
      name: 'MapType',
      position: 'bottomright',
      mapTypes: [
        {
          title: '地图', 
          icon: 'http://api.tianditu.gov.cn/v4.0/image/map/maptype/vector.png',
          layer: 'TMAP_NORMAL_MAP' 
        },
        {
          title: '卫星混合',
          icon: 'http://api.tianditu.gov.cn/v4.0/image/map/maptype/satellitepoi.png',
          layer: 'TMAP_HYBRID_MAP'
        }
      ]
    }
  ]
<tdt-map :controls="mapState.controls" :center="mapState.center" :zoom="mapState.zoom" :mapStyle="mapState.mapStyle">

**Comment by SoulLyoko** [comment]
position是因为官方的api没有提供，mapTypes在v2.7.3中已修复。

**Comment by Haifeng-work** [comment]
官方基类Control， 有方法setPosition(position:enum ControlPosition) 可以对mapType&nbsp;设置位置， 并且测试有效。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SoulLyoko/vue-tianditu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SoulLyoko/vue-tianditu] mapTypes不生效以及position不生效 (Issue #40)





 
position是因为官方的api没有提供，mapTypes在v2.7.3中已修复。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Haifeng-work** [comment]
通过基类方法可以设置位置得， 麻烦作者大大更新下 = =！


------------------&nbsp;原始邮件&nbsp;------------------



发件人:                                                                                                                        "SoulLyoko/vue-tianditu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 上午10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SoulLyoko/vue-tianditu] mapTypes不生效以及position不生效 (Issue #40)





 
Reopened #40.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Haifeng-work** [comment]
![image](https://user-images.githubusercontent.com/22905066/150452671-54c88dcf-4773-4cd9-9429-5d999dc8f33f.png)
通过基类方法可以设置位置得， 麻烦作者大大更新下 = =！

**Comment by SoulLyoko** [comment]
> ![image](https://user-images.githubusercontent.com/22905066/150452671-54c88dcf-4773-4cd9-9429-5d999dc8f33f.png) 通过基类方法可以设置位置得， 麻烦作者大大更新下 = =！

v2.7.4新增position属性
