### ISSUE TITLE
模块 ""vue-tianditu"" 没有导出的成员 "TdtMap"

### ISSUE THREAD

**Issue by ewigl** [SoulLyoko/vue-tianditu#46]
求解惑，这是什么情况，页面中可以正常显示，但是代码报错
![image](https://user-images.githubusercontent.com/43067606/161235434-12d4a3f7-64dc-47fc-b0d8-6f92ef4d1a92.png)
相应的build也会报错
![image](https://user-images.githubusercontent.com/43067606/161235895-ce5d1499-abb2-4d86-a50d-8a8738f7c157.png)
如果去掉大括号，地图就不显示了

**Comment by ackcoder** [comment]
半吊子的我也遇到这个问题，翻源码看了半天。orz
害，其实就是main.ts里app.use全局引入组件了，那么具体vue页面里就没必要写 `import {TdtMap} from 'vue-tianditu'`，直接在`<template>`里用`<tdt-map/>`就是了
