### ISSUE TITLE
你好，如何实现地图移动操作

### ISSUE THREAD

**Issue by caoxiaowei123** [SoulLyoko/vue-tianditu#48]
实现panto操作

**Comment by SoulLyoko** [comment]
![image](https://user-images.githubusercontent.com/48344443/164678308-fa7dceb5-ac98-41d9-8ac1-b32763f345aa.png)
内部是通过监听传入的center和zoom来执行panTo的，所以你只用改变传入给tdt-map的center或zoom，就是执行panTo方法了
