### ISSUE TITLE
如何在初始化的时候更换地图样式呢

### ISSUE THREAD

**Issue by 1005190118** [SoulLyoko/vue-tianditu#5]
如何在初始化的时候更换地图风格呢
map.setStyle('black')

**Comment by SoulLyoko** [comment]
可以在地图初始化事件中做处理:
```
<template>
  <div class="mapDiv">
    <tdt-map :center="center" :zoom="zoom" @init="init"></tdt-map>
  </div>
</template>

<script>
export default {
  name: "ex-map",
  data() {
    return {
      center: [113.280637, 23.125178],
      zoom: 11
    };
  },
  methods: {
    init(map){
      map.setStyle("black")
    }
  }
};
</script>
```

**Comment by sxswwm** [comment]
前辈，这个初始化地图颜色只有“black”吗，没有别的样式吗？我在天地图api上发现indigo颜色挺不错，不过按您的方法setStyle("indigo")显示的还是black

**Comment by SoulLyoko** [comment]
> 前辈，这个初始化地图颜色只有“black”吗，没有别的样式吗？我在天地图api上发现indigo颜色挺不错，不过按您的方法setStyle("indigo")显示的还是black

我这边测试了是可以的哦，你可以把复现的代码贴上来我再测试一下

**Comment by sxswwm** [comment]
![image](https://user-images.githubusercontent.com/51368195/115831427-2925b300-a444-11eb-9caf-2bc6b1d6bd91.png)
我的打开都是这样子的，代码如下：

<template>
  <div class="mapDiv">

    <tdt-map :center="center" :zoom="zoom" :controls="controls" :maxBounds="maxBounds" minZoom="6" @init="init">
      <tdt-control position="topright">
      </tdt-control>
      <div v-for="path in paths" :key="path.id">
        <tdt-polygon :path=path color="black" :opacity="1" :weight="2"></tdt-polygon>
      </div>
      <tdt-marker :position="marker1"></tdt-marker>
    </tdt-map>
  </div>
</template>

<script>
export default {
  name: "ex-map",
  data() {
    return {
      url: 'http://192.168.1.222:8003/all',
      maxBounds: [
        [137, 55], [120, 42]
      ],
      center: [128, 48],
      zoom: 6,
      marker1: [128, 48],
      controls: [{name: "zoom", position: "topleft"}, "scale", "copyright", "overviewMap", "mapType"],
      paths: []
    };
  },
  methods: {
    //init方法
    init(map){
      map.setStyle("indigo");
    },
    // eslint-disable-next-line no-unused-vars
    mapClick(evt) {
      alert("click map");
    }
  },
  created() {
    this.$http.get(this.url).then(res => {
      let i, j;
      // eslint-disable-next-line no-unused-vars
      let k = 0;
      address = new Array(2);
      console.log("总大小为:" + res.data.length)
      for (i = 0; i < 506; i++) {
        var data = res.data[i];
        var address = new Array(2);
        var addresses = new Array(data.address[0].length);//保存读取到的每条数据中的几个经纬度
        for (j = 0; j < data.address[0].length; j++) {
          address[0] = parseFloat(data.address[0][j].jingdu);
          address[1] = parseFloat(data.address[0][j].weidu);
          addresses[j] = JSON.parse(JSON.stringify(address));
        }
        this.paths.push(addresses);
        k++;
        console.log("k的大小为" + k);
      }
    }, err => {
      console.log(err)
    })
  }
};
</script>

**Comment by sxswwm** [comment]
`<template>
  <div class="mapDiv">

    <tdt-map :center="center" :zoom="zoom" :controls="controls" :maxBounds="maxBounds" minZoom="6" @init="init">
      <tdt-control position="topright">
      </tdt-control>
      <div v-for="path in paths" :key="path.id">
        <tdt-polygon :path=path color="black" :opacity="1" :weight="2"></tdt-polygon>
      </div>
      <tdt-marker :position="marker1"></tdt-marker>
    </tdt-map>
  </div>
</template>

<script>
export default {
  name: "ex-map",
  data() {
    return {
      url: 'http://192.168.1.222:8003/all',
      maxBounds: [
        [137, 55], [120, 42]
      ],
      center: [128, 48],
      zoom: 6,
      marker1: [128, 48],
      controls: [{name: "zoom", position: "topleft"}, "scale", "copyright", "overviewMap", "mapType"],
      paths: []
    };
  },
  methods: {
    //init方法
    init(map){
      map.setStyle("indigo");
    },
    // eslint-disable-next-line no-unused-vars
    mapClick(evt) {
      alert("click map");
    }
  },
  created() {
    this.$http.get(this.url).then(res => {
      let i, j;
      // eslint-disable-next-line no-unused-vars
      let k = 0;
      address = new Array(2);
      console.log("总大小为:" + res.data.length)
      for (i = 0; i < 506; i++) {
        var data = res.data[i];
        var address = new Array(2);
        var addresses = new Array(data.address[0].length);//保存读取到的每条数据中的几个经纬度
        for (j = 0; j < data.address[0].length; j++) {
          address[0] = parseFloat(data.address[0][j].jingdu);
          address[1] = parseFloat(data.address[0][j].weidu);
          addresses[j] = JSON.parse(JSON.stringify(address));
        }
        this.paths.push(addresses);
        k++;
        console.log("k的大小为" + k);
      }
    }, err => {
      console.log(err)
    })
  }
};
</script>`

**Comment by sxswwm** [comment]
我的地图样式都长这个样子
![image](https://user-images.githubusercontent.com/51368195/115831913-cbde3180-a444-11eb-802e-7cecedd1f707.png)
代码如下：
'''
<template>
  <div class="mapDiv">

    <tdt-map :center="center" :zoom="zoom" :controls="controls" :maxBounds="maxBounds" minZoom="6" @init="init">
      <tdt-control position="topright">
      </tdt-control>
      <div v-for="path in paths" :key="path.id">
        <tdt-polygon :path=path color="black" :opacity="1" :weight="2"></tdt-polygon>
      </div>
      <tdt-marker :position="marker1"></tdt-marker>
    </tdt-map>
  </div>
</template>

<script>
export default {
  name: "ex-map",
  data() {
    return {
      url: 'http://192.168.1.222:8003/all',
      maxBounds: [
        [137, 55], [120, 42]
      ],
      center: [128, 48],
      zoom: 6,
      marker1: [128, 48],
      controls: [{name: "zoom", position: "topleft"}, "scale", "copyright", "overviewMap", "mapType"],
      paths: []
    };
  },
  methods: {
    //init方法
    init(map){
      map.setStyle("indigo");
    },
    // eslint-disable-next-line no-unused-vars
    mapClick(evt) {
      alert("click map");
    }
  },
  created() {
    this.$http.get(this.url).then(res => {
      let i, j;
      // eslint-disable-next-line no-unused-vars
      let k = 0;
      address = new Array(2);
      console.log("总大小为:" + res.data.length)
      for (i = 0; i < 506; i++) {
        var data = res.data[i];
        var address = new Array(2);
        var addresses = new Array(data.address[0].length);//保存读取到的每条数据中的几个经纬度
        for (j = 0; j < data.address[0].length; j++) {
          address[0] = parseFloat(data.address[0][j].jingdu);
          address[1] = parseFloat(data.address[0][j].weidu);
          addresses[j] = JSON.parse(JSON.stringify(address));
        }
        this.paths.push(addresses);
        k++;
        console.log("k的大小为" + k);
      }
    }, err => {
      console.log(err)
    })
  }
};
</script>
'''
跟您的教程里面的一样，首先@init="init"，然后methods中map.setstyle().

**Comment by SoulLyoko** [comment]
你把

> 我的地图样式都长这个样子
> ![image](https://user-images.githubusercontent.com/51368195/115831913-cbde3180-a444-11eb-802e-7cecedd1f707.png)
> 代码如下：
> '''
> 
> ```
> <template>
> <div class="mapDiv">
> 
> <tdt-map :center="center" :zoom="zoom" :controls="controls" :maxBounds="maxBounds" minZoom="6" @init="init">
> <tdt-control position="topright">
> </tdt-control>
> <div v-for="path in paths" :key="path.id">
> <tdt-polygon :path=path color="black" :opacity="1" :weight="2"></tdt-polygon>
> </div>
> <tdt-marker :position="marker1"></tdt-marker>
> </tdt-map>
> </div>
> </template>
> 
> <script>
> export default {
> name: "ex-map",
> data() {
> return {
> url: 'http://192.168.1.222:8003/all',
> maxBounds: [
> [137, 55], [120, 42]
> ],
> center: [128, 48],
> zoom: 6,
> marker1: [128, 48],
> controls: [{name: "zoom", position: "topleft"}, "scale", "copyright", "overviewMap", "mapType"],
> paths: []
> };
> },
> methods: {
> //init方法
> init(map){
> map.setStyle("indigo");
> },
> // eslint-disable-next-line no-unused-vars
> mapClick(evt) {
> alert("click map");
> }
> },
> created() {
> this.$http.get(this.url).then(res => {
> let i, j;
> // eslint-disable-next-line no-unused-vars
> let k = 0;
> address = new Array(2);
> console.log("总大小为:" + res.data.length)
> for (i = 0; i < 506; i++) {
> var data = res.data[i];
> var address = new Array(2);
> var addresses = new Array(data.address[0].length);//保存读取到的每条数据中的几个经纬度
> for (j = 0; j < data.address[0].length; j++) {
> address[0] = parseFloat(data.address[0][j].jingdu);
> address[1] = parseFloat(data.address[0][j].weidu);
> addresses[j] = JSON.parse(JSON.stringify(address));
> }
> this.paths.push(addresses);
> k++;
> console.log("k的大小为" + k);
> }
> }, err => {
> console.log(err)
> })
> }
> };
> </script>
> ```
> 
> '''
> 跟您的教程里面的一样，首先@init="init"，然后methods中map.setstyle().

你把controls里的 "mapType"和 "overviewMap"调换一下顺序就可以了，这是控件加载顺序的问题

**Comment by SoulLyoko** [comment]
> 前辈，这个初始化地图颜色只有“black”吗，没有别的样式吗？我在天地图api上发现indigo颜色挺不错，不过按您的方法setStyle("indigo")显示的还是black

你把controls里的 "mapType"和 "overviewMap"调换一下顺序就可以了，这是控件加载顺序的问题

**Comment by sxswwm** [comment]
好了，谢谢您，完美解决！！！
我刚才一直不太会把评论里的代码格式化，hhh。
您这个项目真的超级棒，新手用起来很方便，赞一个！！

**Comment by sxswwm** [comment]
对了，还有一个问题，除了普通，黑色，靛蓝色以外，还有别的样式吗

**Comment by SoulLyoko** [comment]
> 对了，还有一个问题，除了普通，黑色，靛蓝色以外，还有别的样式吗

没有了，天地图自带就这三种样式

**Comment by sxswwm** [comment]
> > 对了，还有一个问题，除了普通，黑色，靛蓝色以外，还有别的样式吗
> 
> 没有了，天地图自带就这三种样式

好的，谢谢
