### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by shoukailiang** [SoulLyoko/vue-tianditu#50]
![Uploading image.png…]()
vue 3.0+ts

**Comment by shoukailiang** [comment]
![image](https://user-images.githubusercontent.com/24668909/163329444-b5272e95-fad1-44c9-a559-815ad87c1bb0.png)

**Comment by SoulLyoko** [comment]
可以提供一下node版本吗？输入cmd命令：
```
node -v
```

**Comment by shoukailiang** [comment]
v16.14.0

**Comment by SoulLyoko** [comment]
尝试升级`@types/node`版本解决此问题

**Comment by shoukailiang** [comment]
ok
