### ISSUE TITLE
信息窗口组件的content属性如果是html元素会报错

### ISSUE THREAD

**Issue by huangweigang123** [SoulLyoko/vue-tianditu#53]
![image](https://user-images.githubusercontent.com/47656619/167247082-02e16ec5-76f2-4b1a-bc88-3aa6d648911c.png)
![image](https://user-images.githubusercontent.com/47656619/167247099-5d6fd5e4-75c6-4f8b-93bc-1d93f3492959.png)

如果content属性是引用别的文件组件信息窗口无法弹出，否则虽然报错信息窗口还是能弹出

**Comment by SoulLyoko** [comment]
请问是vue2还是vue3，麻烦提供一下复现的代码

**Comment by huangweigang123** [comment]
是vue2，代码在附件，可以直接运行
如果something换成引入的组件信息窗口就弹不出来了
[index.txt](https://github.com/SoulLyoko/vue-tianditu/files/8644850/index.txt)

> 请问是vue2还是vue3，麻烦提供一下复现的代码

**Comment by SoulLyoko** [comment]
> 是vue2，代码在附件，后缀改成vue可以直接运行 如果something换成引入的组件信息窗口就弹不出来了 [index.txt](https://github.com/SoulLyoko/vue-tianditu/files/8644850/index.txt)
> 
> > 请问是vue2还是vue3，麻烦提供一下复现的代码

- 报错信息只是一个传入类型的警告，下个发布版本就可以修复了。
- 弹窗内容替换成引入的组件的话，我这边测试了是没有问题的，或者你可以给targert属性加上.sync设为双向绑定，并将v-show的判断条件换一下：
```html
<TdtInfowindow
  :target.sync="state.infowindow.target"
  :content="state.infowindow.content"
  :close-on-click="true"
></TdtInfowindow>
<div ref="contentRef" v-show="state.infowindow.target">
  <HelloWorld></HelloWorld>
</div>
```
- infowindow组件支持插槽，可以使用以下写法(建议)：
```html
<TdtInfowindow
  :target.sync="state.infowindow.target"
  :content="state.infowindow.content"
  :close-on-click="true"
>
  <div>
    <HelloWorld></HelloWorld>
  </div>
</TdtInfowindow>
```

**Comment by huangweigang123** [comment]
好的，我这里现在弹窗内容用引入的组件突然能够显示了
