### ISSUE TITLE
mousetool如何定义markTool的事件

### ISSUE THREAD

**Issue by kairsear** [SoulLyoko/vue-tianditu#54]
在tdt-mousetool的示例中，对子对象markTool传参是这样的       <tdt-mousetool ref="mousetoolRef" :markTool="{ follow: true }"></tdt-mousetool>
但是在文档中，对事件markend的调用是如何写的？
比如，按这样写，也是不能触发事件，能否给要一个相关的示例。
:markTool="{ follow: true , markend: onMarkEnd}"

**Comment by SoulLyoko** [comment]
mousetool组件的事件可以通过@事件监听，marktool的事件在文档中有误，下个版本会更新，且会添加到文档示例中
```html
<tdt-mousetool ref="mousetoolRef" :markTool="{ follow: true }" @mark-mouseup="onMarkMouseup"></tdt-mousetool>
```
