### ISSUE TITLE
点聚合组件 tdt-marker-clusterer

### ISSUE THREAD

**Issue by trdmm** [SoulLyoko/vue-tianditu#56]
`clusterer` 这个单词是拼错了还是就是这个啊?
**1.x** 版本是 `cluster`

**Comment by SoulLyoko** [comment]
> `clusterer` 这个单词是拼错了还是就是这个啊? **1.x** 版本是 `cluster`

是clusterer没错，天地图官方也是这个命名。

**Comment by trdmm** [comment]
> > `clusterer` 这个单词是拼错了还是就是这个啊? **1.x** 版本是 `cluster`
> 
> 是clusterer没错，天地图官方也是这个命名。

好吧, 感觉天地图拼错 😭
