### ISSUE TITLE
调用地图的方法示例

### ISSUE THREAD

**Issue by zoe4ems** [SoulLyoko/vue-tianditu#58]
如何调用天地图原生的一些方法呀

**Comment by zoe4ems** [comment]
直接用ref去操作好像不行

**Comment by SoulLyoko** [comment]
- [调用实例方法](https://soullyoko.github.io/vue-tianditu/map/map.html#%E6%89%80%E6%9C%89%E7%BB%84%E4%BB%B6%E9%83%BD%E6%9C%89%E7%9A%84%E4%BA%8B%E4%BB%B6)
- [调用API](https://soullyoko.github.io/vue-tianditu/#api-%E5%8A%A0%E8%BD%BD%E5%99%A8)
