### ISSUE TITLE
调用原生地图方法

### ISSUE THREAD

**Issue by zoe4ems** [SoulLyoko/vue-tianditu#62]
调用原生地图方法能否有一些示例？类似
` let marker = new T.Marker(new T.LngLat(116.411794, 39.9068));`
`//tdMap是tdt-map的ref`
`tdMap.value.addOverLay(marker);`
会报错 T is not defined

**Comment by SoulLyoko** [comment]
调用原生API的方式已添加到文档中：[调用原生API](https://soullyoko.github.io/vue-tianditu/#%E8%B0%83%E7%94%A8%E5%8E%9F%E7%94%9Fapi)
