### ISSUE TITLE
tdt-polyline折线编辑拖动后，如何获取最新坐标点集？

### ISSUE THREAD

**Issue by fire193625** [SoulLyoko/vue-tianditu#63]
tdt-polyline折线编辑拖动后，如何获取最新坐标点集？

没看到相当接口？

**Comment by SoulLyoko** [comment]
> tdt-polyline折线编辑拖动后，如何获取最新坐标点集？
> 
> 没看到相当接口？

你是否是指[mouseup事件](https://soullyoko.github.io/vue-tianditu/overlay/polyline.html#%E4%BA%8B%E4%BB%B6)

**Comment by SoulLyoko** [comment]
> > > tdt-polyline折线编辑拖动后，如何获取最新坐标点集？
> > > 没看到相当接口？
> > 
> > 
> > 你是否是指[mouseup事件](https://soullyoko.github.io/vue-tianditu/overlay/polyline.html#%E4%BA%8B%E4%BB%B6)
> 
> 不是，折线，有一个编辑功能，拖动线上面的小方框，改变线的坐标集合，这拖动不会改变v-model变量的值
> 
> 原生的功能是 ployline.getLngLats() 来获取拖动后的坐标点数组
> 
> 要是您这个VUE 不知如何去获取

天地图官方文档上对于线、面、矩形和圆，没有写明类似于点的drag,dragstart,dragend事件。但经调试测试发现线、面等是有edit事件的，只不过官方文档中未标明。下个版本我会在组件加上这些事件，就可以通过@edit监听来实时获取编辑后的线、面等对象了。

**Comment by fire193625** [comment]
好的，加油，期待您的下一版本！
