### ISSUE TITLE
<tdt-map :center="state.center" :zoom="state.zoom" @init="initMap"></tdt-map> 无法加载地图

### ISSUE THREAD

**Issue by lly1999** [SoulLyoko/vue-tianditu#71]
请问，按照实例方法中初始化地图，地图却未能成功加载。父容器tiandiMap-container已经成功加载占位，只是地图完全不显示
<tdt-map :center="state.center" :zoom="state.zoom" @init="initMap"></tdt-map> 不正确显示地图

**Comment by SoulLyoko** [comment]
试一下给`<tdt-map>`的外部容器添加一个固定的高度：
```html
<div style="height: 400px">
  <tdt-map :center="state.center" :zoom="state.zoom" @init="initMap">
</div>
```

**Comment by lly1999** [comment]
好的，谢谢，这个问题已经解决了。目前还遇到一个问题，在使用车辆轨迹时，按照demo实例引入<tdt-car-track ref="carTrack" :Datas="state.Datas" :interval="5" :speed="10"></tdt-car-track> 后，加载不出来轨迹，控制台报错T.CarTrack is not a constructor，请问是不是天地图官方接口有对车辆轨迹的接口做更新？

**Comment by SoulLyoko** [comment]
不好意思，文档没有写清楚，车辆轨迹是额外的开源库，需要初始化时导入，只是用车辆轨迹的话只要在plugins里传`["CarTrack"]`就可以了
```
app.use(VueTianditu, {
  v: "4.0", //目前只支持4.0版本
  tk: "your map token",
  plugins: ["D3", "CarTrack", "HeatmapOverlay", "BufferTool", "ImageOverLayer"]
});
```

**Comment by lly1999** [comment]
非常感谢大佬，谢谢，问题解决了
